application:
  showGitHubLinks: false
  social:
    questionnaireUrl: null
  welcomeBanner:
    showOnFirstStart: false
challenges:
  showSolvedNotifications: true
  showHints: false
  showFeedbackButtons: false
hackingInstructor:
  isEnabled: false
